Algebraic Bit operations
HigherOrderCO/monobook pull request #19
Opened 2024-09-03 22:30 UTC by Lorenzobattistela

This implements #14 

To run a test example, its possible to use this file on `Bits/Main.agda`:

```agda
module Data.Bits.Main where

open import Data.Bits.Type
open import Data.Bits.add
open import Data.Bits.sub
open import Data.Bits.inc
open import Data.Bits.dec
open import Data.Bits.mul
open import Data.Bits.div
open import Data.Bits.or
open import Data.Bits.not
open import Data.Bits.xor
open import Data.Bits.rshift
open import Data.Bits.lshift
open import Data.Bits.eq
open import Data.IO.Type
open import Data.IO.bind
open import Data.IO.seq
open import Data.IO.put-str-ln
open import Data.String.Type
open import Data.String.append
open import Data.Nat.show
open import Data.Bits.from-nat
open import Data.Bits.and
open import Data.Bits.to-nat
open import Data.Maybe.Type
open import Data.Bool.Type
open import Data.Bool.if

showB : Bits → String
showB E        = "e"
showB (O bits) = showB bits ++ "0"
showB (I bits) = showB bits ++ "1"

showMaybeBits : Maybe Bits → String
showMaybeBits None = "None"
showMaybeBits (Some bits) = showB bits

-- Test function
test : IO _
test = do
  let a = I (O (I E))  -- 101 in binary (5 in decimal)
  let b = I (I (O E))  -- 011 in binary (3 in decimal)
   
  put-str-ln ("a = " ++ showB a ++ " (decimal: " ++ show (to-nat a) ++ ")")
  put-str-ln ("b = " ++ showB b ++ " (decimal: " ++ show (to-nat b) ++ ")")

  let inc_a = inc a
  put-str-ln ("inc a = " ++ showB inc_a ++ " (decimal: " ++ show (to-nat inc_a) ++ ")")

  let dec_b = dec b
  put-str-ln ("dec b = " ++ showB dec_b ++ " (decimal: " ++ show (to-nat dec_b) ++ ")")

  let a_plus_b = a + b
  put-str-ln ("a + b = " ++ showB a_plus_b ++ " (decimal: " ++ show (to-nat a_plus_b) ++ ")")

  let a_minus_b = a - b
  put-str-ln ("a - b = " ++ showB a_minus_b ++ " (decimal: " ++ show (to-nat a_minus_b) ++ ")")

  let a_mul_b = a * b
  put-str-ln ("a * b = " ++ showB a_mul_b ++ " (decimal: " ++ show (to-nat a_mul_b) ++ ")")

  let c = O (I (I E))  -- 110 in binary (6 in decimal)
  put-str-ln ("c = " ++ showB c ++ " (decimal: " ++ show (to-nat c) ++ ")")

  let d = from-nat 0
  put-str-ln ("d = " ++ showB d ++ " (decimal: " ++ show (to-nat d) ++ ")")

  let c_div_b = c / b
  put-str-ln ("c / b = " ++ (showB c_div_b))

  let c_div_zero = c / d
  put-str-ln ("c / d = " ++ (showB c_div_zero))

  -- New tests for logical gates
  let a_and_b = a && b
  put-str-ln ("a && b = " ++ showB a_and_b ++ " (decimal: " ++ show (to-nat a_and_b) ++ ")")

  let a_or_b = a || b
  put-str-ln ("a || b = " ++ showB a_or_b ++ " (decimal: " ++ show (to-nat a_or_b) ++ ")")

  let not_a = ~ a
  put-str-ln ("~a = " ++ showB not_a ++ " (decimal: " ++ show (to-nat not_a) ++ ")")

  let a_xor_b = a ^ b
  put-str-ln ("a ^ b = " ++ showB a_xor_b ++ " (decimal: " ++ show (to-nat a_xor_b) ++ ")")

  let a_eq_b = a == b
  put-str-ln ("a == b = " ++ (if a_eq_b then "True" else "False"))

  let a_eq_a = a == a
  put-str-ln ("a == a = " ++ (if a_eq_a then "True" else "False"))

main : IO _
main = test
```

2024-09-04 20:16 UTC, edusporto commented
Fixed conflict with #18

2024-09-04 20:49 UTC, developedby requested changes

2024-09-04 20:49 UTC, developedby commented on Data/Bits/div.agda
> +divB : Bits → Bits → Bits
Wouldn't it be better to call this `div` and use a renaming import for the Nat.div?

2024-09-04 20:49 UTC, developedby commented on Data/Bits/div.agda
> +divB : Bits → Bits → Bits
I imagine in the future we might want to have some typeclass-like thing for Numbers as well

2024-09-04 20:49 UTC, developedby commented on Data/Bits/mod.agda
> +mod _ E = None
This doesn't terminate for `O E`

2024-09-04 20:49 UTC, developedby commented on Data/Bits/dec.agda
> +dec (I E)  = O E
In some places we're assuming that Bits are implicitly left-padded and that they always have the minimal representation (for example `and`, `or` and `mod`), but here it's done differently

2024-09-04 20:49 UTC, developedby commented on Data/Bits/rshift.agda
> +_>>>_ : Bits → Nat → Bits
Why 3 `>`? If there's a reason (I assume there is), i htink it'd be better to do the same for left shift so that they're similar.

2024-09-04 22:06 UTC, Lorenzobattistela commented on Data/Bits/div.agda
> +divB : Bits → Bits → Bits
Yes, actually i forgot to change this sorry. But typeclasses should fix it as well, thanks for pointing out.

2024-09-04 22:08 UTC, Lorenzobattistela commented on Data/Bits/rshift.agda
> +_>>>_ : Bits → Nat → Bits
name clash with IO/seq, will fix it

But its kinda pain, because you cant use do notation and this operator at the same time

2024-09-05 15:03 UTC, Lorenzobattistela commented on Data/Bits/dec.agda
> +dec (I E)  = O E
@developedby I changed the implementation, but im not sure i interpreted the review correctly in this one

2024-09-05 15:37 UTC, developedby commented on Data/Bits/dec.agda
> +dec (I E)  = O E
There are multiple valid ways of handling this, we just need to make sure that all the Bits function work correctly together.

For example, `div (I E) (dec (inc E))` would not terminate before.

2024-09-05 15:39 UTC, developedby commented on Data/Bits/rshift.agda
> +_>>>_ : Bits → Nat → Bits
I guess you need to rename import when you want to use both. If we add typeclass for sized integers this clash will be inevitable anyway

2024-09-05 16:20 UTC, developedby requested changes

2024-09-05 16:20 UTC, developedby commented on Data/Bits/pad-length.agda
> +pad-length a E = a , E
Isn't this just returning the original values without doing anything? I don't see any padding happening.

2024-09-05 16:20 UTC, developedby commented on Data/Bits/mod.agda
> +mod dividend divisor =
Isn't this slow since it converts back and forth between number and bits for the division? (I imagine bits aren't compiled to an underlying native representation)
I think the old version was probably faster (assymptotically),  you could just convert the initial check for zero by `eq-nat (to-nat divisor) zero`

2024-09-05 16:36 UTC, developedby commented on Data/Bits/mod.agda
> +mod dividend divisor =
Or truncate leading zeros like `strip divisor == E`

2024-09-05 20:17 UTC, developedby commented on Data/Bits/pad-length.agda
> +  in pad-zeros (target-len - len-a) a , pad-zeros (target-len - len-b) b
`pad-zeros` seems to already pad up to the number you pass, so I think you don't need the subtraction

2024-09-06 19:11 UTC, developedby approved these changes

2024-09-06 19:12 UTC, merged