29 json support
HigherOrderCO/monobook pull request #33
Opened 2024-09-09 11:11 UTC by Lorenzobattistela

Implements #29 .

Implements a simple JSON parser. It correctly compiles to haskell through `agda-compile` command. 

The javascript compilation kinda works, but faces the same `bind` problem that is being investigated. (the js compilation is not  a problem since we can just use JSON.parse and JSON.stringify).
Example:

```agda
module Data.JSON.Main where

open import Data.String.Type
open import Data.String.show
open import Data.String.append
open import Data.JSON.Type
open import Data.JSON.parse
open import Data.Parser.State
open import Data.Parser.Error
open import Data.Parser.Reply
open import Data.Result.Type
open import Data.IO.print
open import Data.IO.Type
open import Data.IO.bind
open import Data.IO.seq
open import Data.Unit.Type
open import Data.Function.case
open import Data.JSON.show renaming (show to show-json)

main : IO Unit
main = do
  let json-string = "[1, true, null, [\"nested\", [2.5]], {\"key\": \"value\"}]"
  print ("Parsing JSON string: " ++ show json-string) 
  case parse-json-string json-string of λ where
    (Done reply) → do
      print "Parsing successful!"
      print ("Parsed JSON: " ++ show-json (Reply.value reply))
    (Fail error) → do
      print "Parsing failed!"
```

This compiles correctly to Haskell and parses the JSON. 

**NOTE**: the order of list elements is not preserved.

2024-09-09 11:32 UTC, developedby requested changes

2024-09-09 11:32 UTC, developedby commented on Data/JSON/parse-number.agda
> +
Missing the exponent part.
Can be given as this redex `([eE][+-]?\d+)?`
See https://www.json.org/json-en.html

2024-09-09 11:32 UTC, developedby commented on Data/JSON/parse-object.agda
> +  key ← parse-pstring
This should parse a JSON string.

2024-09-09 11:32 UTC, developedby commented on Data/JSON/parse-string.agda
> +  str ← parse-pstring
I don't know if we want to add support to it right now, but json strings accept some other things
https://www.json.org/json-en.html

2024-09-09 11:32 UTC, developedby commented on Data/List/split-at-element.agda
> +split-at-element : ∀ {A : Set} → (A → A → Bool) → A → List A → Pair (List A) (List A)
An arbitrry design choice, but perhaps a `(A -> Bool) -> List A -> Pair (List A) (List A)` would be better?

Checking every element for some condition. A bit more generic than this function, which would simply be `split-at-element eq x = split (eq x)`

2024-09-10 12:44 UTC, Lorenzobattistela commented on Data/JSON/parse-string.agda
> +  consume "\\"
Maybe we should make sure that the string follows this representation by running `show str` before parsing it, what do you think?

2024-09-10 13:27 UTC, developedby approved these changes

2024-09-10 13:36 UTC, merged