Fix String <-> Bits conversion
HigherOrderCO/monobook pull request #34
Opened 2024-09-09 15:46 UTC by edusporto

Solves #31.

`Char`s in Haskell, and therefore Agda, are Unicode codepoints and can range from 0 to U+10FFFF, so they can span a maxiumum of 21 bits. This PR "solves" the original issue by having each Char always span 21 bits, but that uses up much more memory than necessary for most string we'll actually use.

I thought of two other ways to solve this:

1. Use Bytestrings, available in the Agda stdlib
A minimal implementation can be found in the [bytestring branch](https://github.com/HigherOrderCO/monobook/tree/bytestring). The problem with that is code that compiles directly to GHC or JS won't be reduced by the type system (at least in interactive mode), so code like this won't compile:
```agda
equals1 : to-nat (from-nat 1) == 1
equals1 = refl
-- to-nat (from-nat 1) != 1 of type Nat
```

2. Convert Strings to bytes using the UTF-8 standard
This is possible, especially considering Strings in Agda are already UTF-8 (at least in the Haskell target) since they compile to [Text](https://hackage.haskell.org/package/text-2.1.1/docs/Data-Text.html), but I couldn't find a straight-forward way to do it other than either doing it like option 1 or re-implementing codepoints to bytes like [this Stack Overflow question](https://stackoverflow.com/questions/6240055/manually-converting-unicode-codepoints-into-utf-8-and-utf-16) explains, but that's far from straight-forward.

If we eventually we get slow-downs due to this encoding we could revisit the problem.

2024-09-09 16:24 UTC, developedby requested changes
If the binary representation of strings is supposed to be utf-8, I don't think this is correct.

utf8 adjusts the number of bytes depending on the character and adds a prefix to figure out the byte size of a given code point.

See this for example https://stackoverflow.com/questions/6240055/manually-converting-unicode-codepoints-into-utf-8-and-utf-16#6240819

You can also have a look on how we did it for Bend

2024-09-10 15:42 UTC, edusporto commented
The latest commits does the conversion Bits <-> String in UTF-8, but I think the performance hit on doing these transformation on Bits will probably be too much for the original use case of this feature, which I think was to use Strings as keys of maps. I think we should have both transformations available - a conversion from and to and from UTF-8 and the original simpler conversion. What do you think, @developedby? It's still a bit unclear to me the original intent of this transformation, so unless you know more about it I could also talk to Taelin.

2024-09-10 20:31 UTC, developedby commented on Data/Bits/to-string.agda
> +to-char-list bits = map to-char (reverse (split-chunks 21 bits))
If the bits are in utf-8 then you have to split in chunks of 8 and decode them properly.

Although the max unicode codepoint fits 21 bits, a utf-8 character either occupies 1, 2, 3 or 4 bytes like you seem to have correctly done in your test abo

2024-09-10 21:04 UTC, developedby requested changes
Going through utf-8 should not be a significant slowdown of char to bits conversion. utf-8 is designed to be really fast for both encoding and decoding.

If you're really worried about performance, to decode a utf-8 encoded string as a `Bits`, you only need to check the first 4 bits, look for the pattern and then consume the correct amount of bytes.

2024-09-10 21:04 UTC, developedby commented on Data/Bits/encode-utf8.agda
> +from-char-list char-list = concat (reverse (concat-map encode-char-utf8 char-list))
`encode-char-utf8` should return just Bits and have them in the correct order (MSB first).

Then, `from-char-list` becomes simply `(concat-map encode-char-utf8 char-list)`

Is there some reordering of bytes that i'm not  aware of in UTF-8?

2024-09-10 23:04 UTC, edusporto commented on Data/Bits/to-string.agda
> +to-char-list bits = map to-char (reverse (split-chunks 21 bits))
I actually forgot to delete this file since I renamed the function to `decode-utf8`, sorry

2024-09-11 21:23 UTC, edusporto commented on Data/Bits/decode-char-utf8.agda
> +decode-char-utf8 : List Bits → Pair Char (List Bits)
Improved in the newest commits

2024-09-11 21:25 UTC, edusporto commented on Data/Bits/encode-char-utf8.agda
> +  go : Bits → List Bits
Improved in the newest commits, although changes made today to the Bits module break comparison for Bits with different lengths - I used a new `lte` I created since there was only `lt` for Bits that still works for Bits with different lengths. I'm not sure the reasoning for changing `lt` to how it is now, what do you think we should do in this case?

2024-09-11 21:27 UTC, edusporto commented on Data/Bits/encode-char-utf8.agda
> +  ...   | True = pad-zeros 8 ((from-nat 0xc0) + (oc >> 6)) ::
Changed to something like this in the newest commits.
Although much simpler and easier to read, I believe this new implementation that relies much more on pattern matching should be much slower than one operating with Nats directly, which I think uses Agda builtins to do operation on actual bytes.

The newest commits also use this chained if but in a slightly different way than you presented - precedence with ifs is a bit hard, what I did was the only thing I got to compile.

2024-09-11 21:28 UTC, edusporto commented on Data/Bits/encode-char-utf8.agda
> +encode-char-utf8 : Char → List Bits
Changed in the latest commits

2024-09-11 21:28 UTC, edusporto commented on Data/Bits/encode-utf8.agda
> +from-char-list char-list = concat (reverse (concat-map encode-char-utf8 char-list))
Changed in the latest commits

The large amount of `reverse` calls in the code is because Bits are LSB, which makes all of these operations in UTF-8, designed for MSB, a bit harder.

2024-09-12 10:49 UTC, developedby commented on Data/Bits/encode-utf8.agda
> +from-char-list char-list = concat (reverse (concat-map encode-char-utf8 char-list))
Bits can be LSB or MSB depending on the context, doesn't really matter as long as you use them correctly.

For example if you're reading memory as a `Bits`, it would make sense to keep bits in their original order.

2024-09-12 10:55 UTC, developedby commented on Data/Bits/encode-char-utf8.agda
> +  go : Bits → List Bits
The reason for the change is that a lot of Bits functions were padding and stripping bits which made them more complex than they needed.

Here we could assume that bits are implicitly padded and change 
```
lt E     (O _) = True
```
to
```
lt E     (O b) = lt E b
```

Although we'd need to think about the consequences of this.
See https://github.com/HigherOrderCO/monobook/issues/48

2024-09-12 11:37 UTC, edusporto commented on Data/Bits/encode-utf8.agda
> +from-char-list char-list = concat (reverse (concat-map encode-char-utf8 char-list))
That would break all functions on Bits like `add`, `inc`, `lt`, etc, since they all assume `Bits` are LSB
I think it's only safe to have them be MSB in a private scope, like inside a function (what I'm doing in the `decode-utf8` function)

2024-09-12 11:43 UTC, developedby commented on Data/Bits/encode-char-utf8.agda
> +  if bits <= from-nat 0x7F
Can't you ignore the potential problems of Bits.lt by doing the opposite conversion?
```agda
let bit = from-char c
let n = to-nat c
if n <= 0x7F
  ... -- The if bodies can remain the same
```
You'd also still be able to use the builtin Nat comparisons

2024-09-12 11:43 UTC, developedby commented on Data/Bits/decode-utf8.agda
> +      = to-char (reverse bits₂ ++ reverse bits₁) :: go rest
Very minor, but can you first concat and then reverse?

Slightly more readable that way
```
to-char (reverse (bits1 ++ bits2 ++ bits3 ++ bits4)) :: go rest
```

2024-09-12 13:58 UTC, developedby approved these changes

2024-09-12 13:59 UTC, merged