Add and Test Basic Float Functions
HigherOrderCO/monobook pull request #49
Opened 2024-09-11 15:34 UTC by kings177

Implements #9

There are still tests and bitwise operations to be implemented

2024-09-11 15:50 UTC, developedby requested changes

2024-09-11 15:50 UTC, developedby commented on Data/Float/to-bits.agda
> +to-bits : Float → Maybe U64
The other `to-bits` functions return `Bits`, maybe a `to-u64` and then make this one be something like
```
to-bits : Float -> Bits
to-bits x = case to-u64 x of \ where
  (Some x) -> u64-to-bits x
   None    -> E
```

2024-09-11 15:50 UTC, developedby commented on Data/Float/not.agda
> +-- negates a float
I don't understand what this is supposed to be

2024-09-11 15:50 UTC, developedby commented on Data/Float/not.agda
> +-- negates a float
Is it supposed to be `primFloatNegate`? I don't know what that does either

2024-09-11 15:50 UTC, developedby commented on Data/Float/and.agda
> +float-and : Float → Float → Bool
Why do you call some functions by just their name and other you prepend `float-`?

2024-09-11 15:50 UTC, developedby commented on Data/Float/and.agda
> +-- Performs bitwise AND on two floats.
This description is incorrect

2024-09-11 15:50 UTC, developedby commented on Data/Float/and.agda
> +float-and x y = and (primFloatLess 0.0 x) (primFloatLess 0.0 y)
If this is supposed to be like the C operation, then it should be `x != 0.0 && y != 0`

2024-09-11 15:50 UTC, developedby commented on Data/Float/from-bits.agda
> +from-bits : U64 → Maybe Float
Same thing as the `to-bits`

2024-09-11 15:50 UTC, developedby commented on Data/Float/or.agda
> +-- performs bitwise OR on two floats.
Same comments as `float-and`

2024-09-11 15:50 UTC, developedby commented on Data/Float/xor.agda
> +float-xor : Float → Float → Bool
XOR doesn't make sense for float

2024-09-11 15:57 UTC, kings177 commented on Data/Float/xor.agda
> +float-xor : Float → Float → Bool
i was kinda stuck on that too, since this is basically just a not(equal)

2024-09-11 16:00 UTC, kings177 commented on Data/Float/and.agda
> +float-and : Float → Float → Bool
because agda complains about "multiple definition of ..." (i should just default everything to be "float-" in the beginning since this is the case)

2024-09-11 16:01 UTC, developedby commented on Data/Float/and.agda
> +float-and : Float → Float → Bool
It's better to do `open import ... renaming (and to bool-and)`

That way we don't have to contort our names, which will make it harder if we want to implement these operations as type-classes or similar

2024-09-11 16:02 UTC, kings177 commented on Data/Float/and.agda
> +float-and : Float → Float → Bool
make sense

2024-09-11 16:02 UTC, developedby commented on Data/Float/xor.agda
> +float-xor : Float → Float → Bool
In general you don't want to do bitwise operations on floats since they are kind of meaningless.

It's better to cast to a Word or Bits and then to the bit operations there if we really need to.

2024-09-12 18:02 UTC, developedby requested changes
Remove Operations.agda that defines most of these functions (the primitives) now redundantly.

Check that everything still works.

Also, please consider the unresolved change request about from-bits

2024-09-16 18:54 UTC, developedby requested changes

2024-09-16 18:54 UTC, developedby commented on Data/Float/from-bits.agda
> +        helper None     = 0.0
should probably be NaN

2024-09-16 20:24 UTC, kings177 commented on Data/Float/from-bits.agda
> +        helper None     = 0.0
you mean something like this?

```hs
where
  helper          : Maybe U64 → Maybe Float
  helper (Some x) = Some (from-u64 x)
  helper None     = None
```

2024-09-17 18:12 UTC, developedby commented on Data/Float/from-bits.agda
> +        helper None     = 0.0
No, `from-u64` is interpreting the U64 as an integer and not as a ieee-754 double.

Is this function supposed to read integers or to decode encoded floats?

2024-09-17 20:10 UTC, kings177 commented on Data/Float/from-bits.agda
> +        helper None     = 0.0
`from-u64` is correct for iee-754 doubles. Based on Agda's documentation for word64, the compiler optimizes the conversion to use native 64-bit arithmetic, preserving the original bit pattern.

For `primWord64ToNat`:
> Converting to a natural number is the trivial embedding, and converting from a natural number gives you the remainder modulo 2^{64}.
and so, `primNatToFloat` is operating on a preserved 64-bit representation.

2024-09-17 20:43 UTC, developedby commented on Data/Float/from-bits.agda
> +        helper None     = 0.0
The primitives are so weird, we have `primFloatToWord64` but not the other way around.

`primNatToFloat` but to convert to Nat you need to do floor/round and then convert again.

Can you write some tests for these functions? I don't see anywhere in the documentation indicating that it decodes a Nat as ieee-754

2024-09-18 13:24 UTC, developedby approved these changes
I'll approve it for now since I need this PR for what I'm doing with Bend, but we'll maybe need to come back to the Float <-> Word and Float <-> Bits conversions later.

2024-09-18 13:24 UTC, merged