Add basic arithmetic and bitwise operations for U64 values
HigherOrderCO/monobook pull request #65
Opened 2024-09-16 19:08 UTC by dellamora

Implements #4 

There are still tests to be implemented.

2024-09-16 19:25 UTC, Lorenzobattistela approved these changes

2024-09-16 19:25 UTC, Lorenzobattistela commented on Data/U64/from-bits.agda
> +        helper : Bits → Nat → Maybe U64
maybe use the nat from-bits here?

2024-09-16 19:25 UTC, Lorenzobattistela commented on Data/U64/to-bits.agda
> +to-bits-helper n = do
same here, maybe use the nat wrapper

2024-09-16 19:25 UTC, Lorenzobattistela commented on Data/U64/if.agda
> +open import Data.U64.Type
the only thing i would change here is to use the `if_then_else` infix so we could write
if this
then that
else that 

instead of
if this
this
that

2024-09-16 19:39 UTC, developedby requested changes

2024-09-16 19:39 UTC, developedby commented on Data/U64/and.agda
> +and : U64 → U64 → Bits
Why does this return `Bits` and not `U64`?

2024-09-16 19:39 UTC, developedby commented on Data/U64/lt.agda
> +lt : U64 → U64 → U64
Why does this return `U64` and not `Bool`?

2024-09-16 22:49 UTC, dellamora commented on Data/U64/from-bits.agda
> +        helper : Bits → Nat → Maybe U64
because the conversion can fail if the bit number is greater than U64, or if the bit is invalid, etc. In short, to ensure it follows IEEE 754.

2024-09-16 22:58 UTC, Lorenzobattistela requested changes

2024-09-16 22:58 UTC, Lorenzobattistela commented on Data/U64/lte.agda
> +
still returning U64 here

2024-09-16 22:58 UTC, Lorenzobattistela commented on Data/U64/lte.agda
> +module Data.U64.lte where
also we have lt and lte but not gte

2024-09-16 22:58 UTC, Lorenzobattistela commented on Data/U64/not.agda
> +infix 9 ¬_
maybe use ~ as infix? is this unicode?

2024-09-16 22:58 UTC, Lorenzobattistela commented on Data/U64/or.agda
> +or a b = primWord64FromNat (to-nat ((to-bits a) ||b (to-bits b)))
fix space here a || b

2024-09-16 22:58 UTC, Lorenzobattistela commented on Data/U64/xor.agda
> +xor a b = primWord64FromNat (to-nat ((to-bits a) ^b (to-bits b)))
same here fix spacing ^ b

2024-09-17 00:06 UTC, Lorenzobattistela approved these changes

2024-09-17 10:48 UTC, developedby approved these changes

2024-09-17 11:34 UTC, merged